/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: Ahmad Riazi (https://sketchfab.com/ahmadriazi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/zara-t-shirt-15e8757908094027ad8352b890942979
Title: Zara T_shirt
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ rotation, ...props }) {
  const { nodes, materials } = useGLTF("/scene.gltf");
  materials.invertNormalMapX = true;
  return (
    <group {...props} dispose={null} rotation={rotation}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={0.001}>
          <mesh
            geometry={nodes.Object_5.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            geometry={nodes.Object_7.geometry}
            material={materials.material_0}
          />

          <mesh
            geometry={nodes.Object_11.geometry}
            material={materials["Material.002"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
